### ISSUE TITLE
Can't play any games

### ISSUE THREAD

**Issue by crazyhorse77** [glennguy/plugin.video.nrl-live#2]
I rechecked my username and password and phone number but I get this in the log:

19:53:00.080 T:17088   ERROR: C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py:155: FutureWarning: The behavior of this method will change in future versions.  Use specific 'len(elem)' or 'elem is not None' test instead.
                                              if gm.find('Description'):
19:53:02.710 T:5260   ERROR: C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
19:53:04.609 T:5260   ERROR: Previous line repeats 3 times.
19:53:04.610 T:5260   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidHeader'>
                                            Error Contents: Invalid return character or leading space in header: Authorization
                                            Traceback (most recent call last):
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 343, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 331, in router
                                                play_video(params['id'], params['live'])
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 272, in play_video
                                                loginToken = ooyalahelper.get_nrl_user_token(username, password, phone_number)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\resources\lib\ooyalahelper.py", line 60, in get_nrl_user_token
                                                return telstra_auth.get_token(username, password, phone_number)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\resources\lib\telstra_auth.py", line 70, in get_token
                                                phone_number, offer_id, token))
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 535, in post
                                                return self.request('POST', url, data=data, json=json, **kwargs)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 474, in request
                                                prep = self.prepare_request(req)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 407, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 303, in prepare
                                                self.prepare_headers(headers)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\models.py", line 427, in prepare_headers
                                                check_header_validity(header)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\utils.py", line 793, in check_header_validity
                                                raise InvalidHeader("Invalid return character or leading space in header: %s" % name)
                                            InvalidHeader: Invalid return character or leading space in header: Authorization
                                            -->End of Python script error report<--
19:53:04.703 T:18884   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nrl-live/?action=parseround&year=2014&rnd=26&gm=Rd 26: Cowboys v Sea Eagles (1)&id=hwM2E1cDqeADc104-nPtxkRVO-SAgop2&live=false&thumb=http://bigpondvideo.com/Web/Images/Content/20140906223741a_326x184.jpg&time=9/7/2014 • 9:30 AM&score=None]

**Comment by glennguy** [comment]
Hi @crazyhorse77 can you try the latest changes? Just a stab in the dark but hopefully it will at least rule something out if it still isn't working.

**Comment by crazyhorse77** [comment]
Thanks for looking at it.

Updated and now get this.

21:07:24.703 T:4440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 343, in <module>
                                                router(sys.argv[2][1:])
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 331, in router
                                                play_video(params['id'], params['live'])
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\default.py", line 272, in play_video
                                                loginToken = ooyalahelper.get_nrl_user_token(username, password, phone_number)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\resources\lib\ooyalahelper.py", line 60, in get_nrl_user_token
                                                return telstra_auth.get_token(username, password, phone_number)
                                              File "C:\Users\Anthony\AppData\Roaming\Kodi\addons\plugin.video.nrl-live\resources\lib\telstra_auth.py", line 50, in get_token
                                                saml_response = soup.find(attrs={'name': 'SAMLResponse'}).get('value')
                                            AttributeError: 'NoneType' object has no attribute 'get'
                                            -->End of Python script error report<--
21:07:24.785 T:18092   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nrl-live/?action=parseround&year=2016&rnd=30&gm=GF: Storm v Sharks (2)&id=F2M3g3NjE6qtRPhX4TEdx0kHSYVOuw9A&live=false&thumb=http://bigpondvideo.com/web/images/content/20161002213013a_326x184.jpg&time=10/3/2016 • 10:00 AM&score=None]

**Comment by crazyhorse77** [comment]
Sorry but could be a problem with my account. Says it is activated, but just tried to play a game through the NRL Live App, but only got a 2 min preview and it asked me to subscribe. I will look it this further. Thanks.

**Comment by glennguy** [comment]
The telstra ID that you use in the add-on needs to have an eligible phone
number linked to it. Log on at Telstra.com.au with your ID and check there.

**Comment by crazyhorse77** [comment]
Thanks I now have it sorted and it is working! Awesome work.
